name: admin_events
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5
  freezed_annotation: ^2.4.4
  flutter_bloc: ^8.1.6
  rxdart: ^0.28.0

  auto_route: ^9.1.0
  google_fonts: ^6.2.1

  flutter_web_qrcode_scanner: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  build_runner: ^2.4.11
  freezed: ^2.5.2
  auto_route_generator: ^9.0.0
  unused_import_remover: ^1.0.1


flutter:

  uses-material-design: true

  assets:
    - assets/